idk

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,6 +4,10 @@ on:
   push:
     branches: [main]
 
+permissions:
+  contents: write
+  pages: write
+
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
@@ -21,6 +25,9 @@ jobs:
         
       - name: Build
         run: npm run build
+
+      - name: Check out directory
+        run: ls -la out || echo "out folder not found"
         
       - name: Deploy to GitHub Pages
         uses: peaceiris/actions-gh-pages@v3
